### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by wirescarryingme** [dlccyes/obsidian-nebula#2]
I can no longer open my settings when I installed this theme. How do I uninstall this theme?

**Comment by dlccyes** [comment]
The default keyboard shortcut for opening the settings is `Ctrl+,`. Or you can just open your command palette (default is `Ctrl+P`) and type "settings").

You can also straight up delete the theme file in `.obsidian/themes/Nebula.css`.

The reason I hide the leftmost vertical bar is that I use shortcut keys or command palette to go to everything lol. If you rely heavily on your mouse, then the theme is not for you.

If you're familiar with CSS and want to keep using this theme with the leftmost vertical bar displayed, you can adjust the CSS class `side-dock-ribbon`, `side-dock-ribbon-tab` and `side-dock-ribbon-action`  yourself.
